# Generated by Django 2.2.16 on 2022-07-07 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=15, verbose_name='IP address')),
                ('port', models.IntegerField(verbose_name='Port')),
                ('resourse_type', models.CharField(choices=[('WINDOWS', 'Windows'), ('UNIX', 'Unix'), ('SQL', 'Sql')], default='WINDOWS', max_length=10, verbose_name='Resourse type')),
                ('change_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Date of last changing')),
                ('host_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resourse', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
